# EC3 storefronts
<VirtualHost *:80>
    ServerName theme1.ecommerce.test
    ServerAlias theme1.localhost
    DocumentRoot "/Applications/XAMPP/xamppfiles/htdocs/ec3"
    <Directory "/Applications/XAMPP/xamppfiles/htdocs/ec3">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog "logs/theme1.ecommerce.test-error.log"
    CustomLog "logs/theme1.ecommerce.test-access.log" common
</VirtualHost>

<VirtualHost *:80>
    ServerName theme2.ecommerce.test
    ServerAlias theme2.localhost
    DocumentRoot "/Applications/XAMPP/xamppfiles/htdocs/ec3"
    <Directory "/Applications/XAMPP/xamppfiles/htdocs/ec3">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog "logs/theme2.ecommerce.test-error.log"
    CustomLog "logs/theme2.ecommerce.test-access.log" common
</VirtualHost>

<VirtualHost *:80>
    ServerName fruitables.ecommerce.test
    ServerAlias fruitables.localhost
    DocumentRoot "/Applications/XAMPP/xamppfiles/htdocs/ec3"
    <Directory "/Applications/XAMPP/xamppfiles/htdocs/ec3">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog "logs/fruitables.ecommerce.test-error.log"
    CustomLog "logs/fruitables.ecommerce.test-access.log" common
</VirtualHost>

<VirtualHost *:80>
    ServerName zenvello.ecommerce.test
    ServerAlias zenvello.localhost
    DocumentRoot "/Applications/XAMPP/xamppfiles/htdocs/ec3"
    <Directory "/Applications/XAMPP/xamppfiles/htdocs/ec3">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog "logs/zenvello.ecommerce.test-error.log"
    CustomLog "logs/zenvello.ecommerce.test-access.log" common
</VirtualHost>

<VirtualHost *:80>
    ServerName cartvibe.co.uk
    ServerAlias www.cartvibe.co.uk cartvibe.localhost cartvibe.ecommerce.test
    DocumentRoot "/Applications/XAMPP/xamppfiles/htdocs/ec3"
    <Directory "/Applications/XAMPP/xamppfiles/htdocs/ec3">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog "logs/cartvibe.co.uk-error.log"
    CustomLog "logs/cartvibe.co.uk-access.log" common
</VirtualHost>

<VirtualHost *:80>
    ServerName zenvello.se
    ServerAlias www.zenvello.se zenvellose.localhost zenvellose.ecommerce.test
    DocumentRoot "/Applications/XAMPP/xamppfiles/htdocs/ec3"
    <Directory "/Applications/XAMPP/xamppfiles/htdocs/ec3">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog "logs/zenvello.se-error.log"
    CustomLog "logs/zenvello.se-access.log" common
</VirtualHost>
