server {
    listen 80;
    listen [::]:80;
    server_name cartvibe.co.uk www.cartvibe.co.uk;

    root /var/www/projects/zenvello.co.uk;
    index index.php index.html index.htm;

    access_log /var/log/nginx/cartvibe.co.uk.access.log;
    error_log  /var/log/nginx/cartvibe.co.uk.error.log;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ ^/(application|system|db|deploy)/ {
        deny all;
    }

    location ~* \.(sql|pem|md)$ {
        deny all;
    }

    location = /config.php {
        deny all;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    client_max_body_size 64M;
}
