-- Per-store Meta / TikTok sales channel connections (OAuth, no merchant API keys)

CREATE TABLE IF NOT EXISTS `store_channel_connections` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `store_id` int(10) unsigned NOT NULL,
  `platform` varchar(20) NOT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'disconnected',
  `access_token` text DEFAULT NULL,
  `refresh_token` text DEFAULT NULL,
  `token_expires_at` datetime DEFAULT NULL,
  `external_user_id` varchar(64) DEFAULT NULL,
  `business_id` varchar(64) DEFAULT NULL,
  `business_name` varchar(255) DEFAULT NULL,
  `page_id` varchar(64) DEFAULT NULL,
  `page_name` varchar(255) DEFAULT NULL,
  `page_token` text DEFAULT NULL,
  `instagram_id` varchar(64) DEFAULT NULL,
  `instagram_username` varchar(255) DEFAULT NULL,
  `catalog_id` varchar(64) DEFAULT NULL,
  `catalog_name` varchar(255) DEFAULT NULL,
  `pixel_id` varchar(64) DEFAULT NULL,
  `pixel_name` varchar(255) DEFAULT NULL,
  `ad_account_id` varchar(64) DEFAULT NULL,
  `advertiser_id` varchar(64) DEFAULT NULL,
  `advertiser_name` varchar(255) DEFAULT NULL,
  `extra_json` mediumtext DEFAULT NULL,
  `last_sync_at` datetime DEFAULT NULL,
  `last_error` text DEFAULT NULL,
  `connected_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `store_platform` (`store_id`,`platform`),
  KEY `platform` (`platform`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `store_channel_jobs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `store_id` int(10) unsigned NOT NULL,
  `platform` varchar(20) NOT NULL DEFAULT '',
  `job_type` varchar(40) NOT NULL,
  `payload` mediumtext DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'queued',
  `attempts` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `available_at` datetime DEFAULT NULL,
  `last_error` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `due` (`status`,`available_at`),
  KEY `store_platform` (`store_id`,`platform`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
